//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamantWinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class boleta
    {
        public int bol_serie { get; set; }
        public Nullable<int> bolsoc_id { get; set; }
        public Nullable<int> bolpro_id { get; set; }
        public Nullable<int> bollug_id { get; set; }
        public Nullable<System.DateTime> bol_fecha { get; set; }
    
        public virtual lugar lugar { get; set; }
        public virtual producto producto { get; set; }
        public virtual socio socio { get; set; }
    }
}
