//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamantWinForms
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntregaProductoEntities : DbContext
    {
        public EntregaProductoEntities()
            : base("name=EntregaProductoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<boleta> boletas { get; set; }
        public virtual DbSet<dedo> dedoes { get; set; }
        public virtual DbSet<dedo_Socio> dedo_Socio { get; set; }
        public virtual DbSet<lugar> lugars { get; set; }
        public virtual DbSet<producto> productoes { get; set; }
        public virtual DbSet<socio> socios { get; set; }
    }
}
