//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamantWinForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class socio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public socio()
        {
            this.boletas = new HashSet<boleta>();
            this.dedo_Socio = new HashSet<dedo_Socio>();
        }
    
        public int soc_id { get; set; }
        public string soc_rut { get; set; }
        public string soc_nombre { get; set; }
        public string soc_ape_paterno { get; set; }
        public string soc_ape_materno { get; set; }
        public string soc_cumple { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boleta> boletas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dedo_Socio> dedo_Socio { get; set; }
    }
}
